dataset:
  name: "persons"
  location: "/cache/datasets/persons/dataset"
  workers: 3 # number of threads to get data
  img_means: #rgb
    - 0.2868
    - 0.3251
    - 0.2838
  img_stds: #rgb
    - 0.1869
    - 0.1901
    - 0.1872
  img_prop:
    width: 1024
    height: 512
    depth: 3
  labels:
    0: 'road'
    1: 'sidewalk'
    2: 'building'
    3: 'wall'
    4: 'fence'
    5: 'pole'
    6: 'trafficlight'
    7: 'trafficsign'
    8: 'vegetation'
    9: 'terrain'
    10: 'sky'
    11: 'person'
    12: 'rider'
    13: 'car'
    14: 'truck'
    15: 'bus'
    16: 'train'
    17: 'motorcycle'
    18: 'bicycle'
    19: 'crap'
  our_label:
    person: [60,20,220]
    
  color_map: # bgr
    0: [128,64,128]
    1: [232,35,244]
    2: [70,70,70]
    3: [156,102,102]
    4: [153,153,190]
    5: [153,153,153]
    6: [30,170,250]
    7: [0,220,220]
    8: [35,142,107]
    9: [152,251,152]
    10: [180,130,70]
    11: [60,20,220]
    12: [0,0,255]
    13: [142,0,0]
    14: [70,0,0]
    15: [100,60,0]
    16: [100,80,0]
    17: [230,0,0]
    18: [32,11,119]
    19: [0,0,0]
    